# output/formatter.py
"""Formatting helpers for risk scores, levels, and CLI briefing output."""

from __future__ import annotations

import json
from typing import Any, Dict, Optional


RISK_LEVEL_COLORS = {
    "CRITICAL": "#DC2626",  # Red
    "HIGH":     "#F97316",  # Orange
    "MEDIUM":   "#EAB308",  # Yellow
    "LOW":      "#22C55E",  # Green
    "UNKNOWN":  "#6B7280",  # Gray
}

RISK_LEVEL_EMOJI = {
    "CRITICAL": "🔴",
    "HIGH":     "🟠",
    "MEDIUM":   "🟡",
    "LOW":      "🟢",
    "UNKNOWN":  "⚪",
}


def format_percentage(value: Optional[float], decimals: int = 2) -> str:
    """Format a fraction as a percentage string, e.g. 0.0234 → '2.34%'."""
    if value is None:
        return "N/A"
    return f"{value * 100:.{decimals}f}%"


def format_score(value: Optional[float]) -> str:
    """Format a 0-100 risk score."""
    if value is None:
        return "N/A"
    return f"{value:.1f}/100"


def format_risk_level(level: Optional[str]) -> str:
    """Format risk level with emoji indicator."""
    if not level:
        return "UNKNOWN"
    emoji = RISK_LEVEL_EMOJI.get(level, "⚪")
    return f"{emoji} {level}"


def briefing_to_summary_text(briefing: Dict[str, Any]) -> str:
    """Render a briefing as a human-readable text summary (for CLI output)."""
    lines = []
    meta = briefing.get("metadata", {})
    overall = briefing.get("overall_risk", {})
    breakdown = briefing.get("risk_breakdown", {})

    lines.append("=" * 70)
    lines.append("RISKLENS — RISK INTELLIGENCE BRIEFING")
    lines.append(f"Date: {meta.get('date', 'N/A')}  |  Portfolio: {meta.get('portfolio_id', 'N/A')}")
    lines.append("=" * 70)
    lines.append("")
    lines.append(f"EXECUTIVE SUMMARY")
    lines.append("-" * 40)
    lines.append(briefing.get("executive_summary", "No summary available."))
    lines.append("")
    lines.append(f"OVERALL RISK:  {format_risk_level(overall.get('level'))}  |  Score: {format_score(overall.get('score'))}  |  Trend: {overall.get('trend', 'N/A')}")
    lines.append("")
    lines.append("PILLAR BREAKDOWN:")
    for pillar, data in breakdown.items():
        pillar_label = pillar.replace("_", " ").upper()
        level = data.get("level", "N/A")
        score = data.get("score", 0)
        lines.append(f"  {pillar_label:<22} {format_risk_level(level):<15} {score:.1f}/100")

    lines.append("")
    top_risks = briefing.get("top_risks", [])
    if top_risks:
        lines.append("TOP RISKS:")
        for risk in top_risks[:5]:
            lines.append(f"  [{risk.get('rank', '?')}] {risk.get('risk', '')[:80]}")

    lines.append("")
    recommendations = briefing.get("recommended_actions", [])
    if recommendations:
        lines.append("RECOMMENDED ACTIONS:")
        for rec in recommendations[:5]:
            urgency = rec.get("urgency", "")
            lines.append(f"  [{urgency}] {rec.get('action', '')}")

    lines.append("")
    if briefing.get("analyst_notes"):
        lines.append(f"ANALYST NOTES: {briefing['analyst_notes']}")
        lines.append("")

    lines.append("=" * 70)
    lines.append("Generated by RiskLens v1.0 — For internal use only")
    lines.append("=" * 70)

    return "\n".join(lines)


def briefing_to_json(briefing: Dict[str, Any], indent: int = 2) -> str:
    """Serialise briefing to JSON string."""
    return json.dumps(briefing, indent=indent, default=str)
