# output/pdf_generator.py
"""PDF generator — produces a multi-page bank-style risk briefing using ReportLab."""

from __future__ import annotations

import logging
import os
from datetime import datetime
from typing import Any, Dict, List, Optional

from core.config import BRIEFINGS_DIR, PDF_CONFIDENTIAL_WATERMARK, PDF_LOGO_TEXT

logger = logging.getLogger(__name__)

# Colour palette (R, G, B each 0-1)
COLOUR = {
    "CRITICAL":     (0.86, 0.15, 0.15),
    "HIGH":         (0.98, 0.57, 0.09),
    "MEDIUM":       (0.92, 0.70, 0.03),
    "LOW":          (0.13, 0.77, 0.37),
    "DARK_BG":      (0.07, 0.07, 0.12),
    "LIGHT_TEXT":   (0.95, 0.95, 0.95),
    "ACCENT_BLUE":  (0.20, 0.40, 0.80),
    "MID_GRAY":     (0.45, 0.45, 0.45),
    "LIGHT_GRAY":   (0.90, 0.90, 0.92),
    "WHITE":        (1.00, 1.00, 1.00),
    "BLACK":        (0.00, 0.00, 0.00),
}


def _rgb(key: str):
    """Return a ReportLab Color from the palette."""
    from reportlab.lib.colors import Color
    r, g, b = COLOUR[key]
    return Color(r, g, b)


def _risk_color(level: str):
    """Map a risk level string to its ReportLab Color."""
    key = level.upper() if level and level.upper() in COLOUR else "MID_GRAY"
    return _rgb(key)


def generate_pdf(briefing: Dict[str, Any], output_path: Optional[str] = None) -> str:
    """Generate PDF from briefing dict. Returns the output file path."""
    try:
        from reportlab.lib import colors
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import cm
        from reportlab.platypus import (
            Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle, PageBreak
        )
        from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
    except ImportError:
        logger.error("reportlab not installed — PDF generation unavailable. Run: pip install reportlab")
        return ""

    meta = briefing.get("metadata", {})
    analysis_date = meta.get("date", datetime.today().strftime("%Y-%m-%d"))

    if not output_path:
        os.makedirs(BRIEFINGS_DIR, exist_ok=True)
        filename = f"RiskLens_Briefing_{analysis_date}_{datetime.now().strftime('%H%M%S')}.pdf"
        output_path = os.path.join(BRIEFINGS_DIR, filename)

    doc = SimpleDocTemplate(
        output_path,
        pagesize=A4,
        rightMargin=2 * cm,
        leftMargin=2 * cm,
        topMargin=2.5 * cm,
        bottomMargin=2.5 * cm,
    )

    styles = getSampleStyleSheet()
    story = []

    # Custom styles
    title_style = ParagraphStyle("Title", parent=styles["Title"], fontSize=28, spaceAfter=6, textColor=_rgb("ACCENT_BLUE"))
    subtitle_style = ParagraphStyle("Subtitle", parent=styles["Normal"], fontSize=13, textColor=_rgb("MID_GRAY"), spaceAfter=4)
    heading_style = ParagraphStyle("Heading", parent=styles["Heading1"], fontSize=14, textColor=_rgb("ACCENT_BLUE"), spaceBefore=12, spaceAfter=6)
    body_style = ParagraphStyle("Body", parent=styles["Normal"], fontSize=10, leading=14, spaceAfter=6)
    flag_style = ParagraphStyle("Flag", parent=styles["Normal"], fontSize=9, leading=12, textColor=_rgb("CRITICAL"), spaceAfter=3)
    small_style = ParagraphStyle("Small", parent=styles["Normal"], fontSize=8, textColor=_rgb("MID_GRAY"))

    # cover page
    story.append(Spacer(1, 3 * cm))
    story.append(Paragraph(PDF_LOGO_TEXT, title_style))
    story.append(Paragraph("Risk Intelligence Briefing", subtitle_style))
    story.append(Spacer(1, 0.5 * cm))

    overall = briefing.get("overall_risk", {})
    level = overall.get("level", "UNKNOWN")
    score = overall.get("score", 0)

    # Risk level badge (coloured table cell)
    badge_data = [[Paragraph(f"<b>{level}</b>  {score:.1f}/100", ParagraphStyle("Badge", parent=styles["Normal"], fontSize=18, textColor=_rgb("WHITE"), alignment=TA_CENTER))]]
    badge_table = Table(badge_data, colWidths=[10 * cm])
    badge_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), _risk_color(level)),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 14),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 14),
        ("ROUNDEDCORNERS", [6, 6, 6, 6]),
    ]))
    story.append(badge_table)
    story.append(Spacer(1, 1 * cm))

    cover_info = [
        ["Date:", analysis_date],
        ["Portfolio ID:", meta.get("portfolio_id", "N/A")],
        ["Generated by:", meta.get("generated_by", "RiskLens")],
        ["Analyst Review:", meta.get("analyst_reviewed", "Not required")],
        ["Trend:", overall.get("trend", "N/A")],
    ]
    cover_table = Table(cover_info, colWidths=[4 * cm, 8 * cm])
    cover_table.setStyle(TableStyle([
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("TEXTCOLOR", (0, 0), (0, -1), _rgb("ACCENT_BLUE")),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    story.append(cover_table)
    story.append(Spacer(1, 2 * cm))
    story.append(Paragraph(PDF_CONFIDENTIAL_WATERMARK, ParagraphStyle("Watermark", parent=styles["Normal"], fontSize=9, textColor=_rgb("MID_GRAY"), alignment=TA_CENTER)))
    story.append(PageBreak())

    # executive summary + pillar breakdown
    story.append(Paragraph("Executive Summary", heading_style))
    exec_text = briefing.get("executive_summary", "No summary available.")
    story.append(Paragraph(exec_text, body_style))
    story.append(Spacer(1, 0.5 * cm))

    story.append(Paragraph("Risk Pillar Breakdown", heading_style))
    breakdown = briefing.get("risk_breakdown", {})
    breakdown_data = [["Pillar", "Score", "Level", "Top Flag"]]
    for pillar_key, pdata in breakdown.items():
        pillar_name = pillar_key.replace("_", " ").title()
        pillar_score = f"{pdata.get('score', 0):.1f}"
        pillar_level = pdata.get("level", "N/A")
        top_flag = (pdata.get("flags") or ["None"])[0][:60]
        breakdown_data.append([pillar_name, pillar_score, pillar_level, top_flag])

    breakdown_table = Table(breakdown_data, colWidths=[4 * cm, 2 * cm, 2.5 * cm, 9 * cm])
    breakdown_table.setStyle(_build_pillar_table_style(breakdown))
    story.append(breakdown_table)
    story.append(PageBreak())

    # top risk findings
    story.append(Paragraph("Top Risk Findings", heading_style))
    top_risks = briefing.get("top_risks", [])
    for risk in top_risks:
        rank = risk.get("rank", "?")
        risk_text = risk.get("risk", "")
        driver = risk.get("driver", "")
        severity = risk.get("severity", "")
        reg_ref = risk.get("regulatory_ref", "")[:200]

        risk_para_style = ParagraphStyle(f"Risk{rank}", parent=body_style, textColor=_risk_color(severity))
        story.append(Paragraph(f"<b>[{rank}] {risk_text}</b>", risk_para_style))
        story.append(Paragraph(f"Pillar: {driver} | Severity: {severity}", small_style))
        story.append(Paragraph(f"Reg. Ref: {reg_ref}", small_style))
        story.append(Spacer(1, 0.3 * cm))

    story.append(PageBreak())

    # recommended actions
    story.append(Paragraph("Recommended Actions", heading_style))
    recommendations = briefing.get("recommended_actions", [])
    rec_data = [["Urgency", "Action", "Pillar"]]
    for rec in recommendations:
        rec_data.append([
            rec.get("urgency", ""),
            Paragraph(rec.get("action", "")[:80], body_style),
            rec.get("pillar", ""),
        ])
    rec_table = Table(rec_data, colWidths=[2 * cm, 11 * cm, 4 * cm])
    rec_table.setStyle(TableStyle([
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("BACKGROUND", (0, 0), (-1, 0), _rgb("ACCENT_BLUE")),
        ("TEXTCOLOR", (0, 0), (-1, 0), _rgb("WHITE")),
        ("GRID", (0, 0), (-1, -1), 0.5, _rgb("LIGHT_GRAY")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [_rgb("WHITE"), _rgb("LIGHT_GRAY")]),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ]))
    story.append(rec_table)
    story.append(PageBreak())

    # position-level details
    story.append(Paragraph("Position-Level Details", heading_style))
    position_details = briefing.get("position_details", [])
    pos_data = [["Ticker", "Name", "Wt%", "Vol%", "Drawdown", "Beta", "Credit"]]
    for pos in position_details:
        vol = pos.get("annualised_vol")
        dd = pos.get("max_drawdown")
        beta = pos.get("beta")
        pos_data.append([
            pos.get("ticker", ""),
            pos.get("name", "")[:20],
            f"{pos.get('weight', 0)*100:.1f}%",
            f"{vol*100:.1f}%" if vol else "N/A",
            f"{dd*100:.1f}%" if dd else "N/A",
            f"{beta:.2f}" if beta else "N/A",
            pos.get("credit_grade", "N/A"),
        ])

    pos_table = Table(pos_data, colWidths=[2 * cm, 5 * cm, 1.5 * cm, 2 * cm, 2.5 * cm, 1.5 * cm, 2 * cm])
    pos_table.setStyle(TableStyle([
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("BACKGROUND", (0, 0), (-1, 0), _rgb("ACCENT_BLUE")),
        ("TEXTCOLOR", (0, 0), (-1, 0), _rgb("WHITE")),
        ("GRID", (0, 0), (-1, -1), 0.5, _rgb("LIGHT_GRAY")),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [_rgb("WHITE"), _rgb("LIGHT_GRAY")]),
        ("ALIGN", (2, 0), (-1, -1), "RIGHT"),
    ]))
    story.append(pos_table)
    story.append(PageBreak())

    # regulatory citations
    story.append(Paragraph("Regulatory References (Basel III/IV)", heading_style))
    citations = briefing.get("regulatory_citations", [])
    if citations:
        for i, citation in enumerate(citations, 1):
            story.append(Paragraph(f"<b>Citation {i}:</b>", body_style))
            story.append(Paragraph(citation[:800], small_style))
            story.append(Spacer(1, 0.4 * cm))
    else:
        story.append(Paragraph("No regulatory citations retrieved (RAG index may not be built).", body_style))

    if briefing.get("analyst_notes"):
        story.append(Spacer(1, 0.5 * cm))
        story.append(Paragraph("Analyst Notes", heading_style))
        story.append(Paragraph(briefing["analyst_notes"], body_style))

    # Build PDF
    doc.build(story, onFirstPage=_add_footer, onLaterPages=_add_footer)
    logger.info("PDF generated at %s", output_path)
    return output_path


def _add_footer(canvas, doc):
    """Add footer to every page."""
    from reportlab.lib.pagesizes import A4
    canvas.saveState()
    canvas.setFont("Helvetica", 8)
    canvas.setFillColorRGB(*COLOUR["MID_GRAY"])
    footer_text = f"Generated by RiskLens  |  For internal use only  |  {datetime.today().strftime('%Y-%m-%d')}"
    canvas.drawCentredString(A4[0] / 2, 1.2 * 28.35, footer_text)  # 1.2cm from bottom
    canvas.drawRightString(A4[0] - 2 * 28.35, 1.2 * 28.35, f"Page {doc.page}")
    canvas.restoreState()


def _build_pillar_table_style(breakdown: Dict) -> Any:
    """Build dynamic table style for the pillar breakdown table with colour-coded level cells."""
    from reportlab.platypus import TableStyle

    base_style = [
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("BACKGROUND", (0, 0), (-1, 0), _rgb("ACCENT_BLUE")),
        ("TEXTCOLOR", (0, 0), (-1, 0), _rgb("WHITE")),
        ("GRID", (0, 0), (-1, -1), 0.5, _rgb("LIGHT_GRAY")),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]

    for i, (pillar_key, pdata) in enumerate(breakdown.items(), start=1):
        level = pdata.get("level", "UNKNOWN")
        base_style.append(("BACKGROUND", (2, i), (2, i), _risk_color(level)))
        base_style.append(("TEXTCOLOR", (2, i), (2, i), _rgb("WHITE")))
        base_style.append(("FONTNAME", (2, i), (2, i), "Helvetica-Bold"))

    return TableStyle(base_style)
